cb_ai_vehs: true
cb_aim: true
cb_armor: true
cb_bkgd: true
cb_books_history: true
cb_cab_cargo: true
cb_clans: true
cb_controls: true
cb_crashes: true
cb_descriptions: true
cb_dialogues: true
cb_digits: true
cb_dwellers: true
cb_engines: true
cb_env_models: true
cb_env_textures: true
cb_explosions: true
cb_fadingmsgs: true
cb_fov: true
cb_goods_guns: true
cb_gravity: true
cb_gui_icons: true
cb_gui_text: true
cb_guns: true
cb_guns_lua: true
cb_hits: true
cb_horns: true
cb_humans: true
cb_landscape: true
cb_lightmaps: true
cb_maps: true
cb_masks: true
cb_music: true
cb_names: true
cb_npc_look: true
cb_other_sounds: true
cb_pl_veh: true
cb_quests: true
cb_radar: true
cb_radio: true
cb_render: true
cb_shooting: true
cb_skybox: true
cb_speech: true
cb_splashes: true
cb_tiles: true
cb_towns: true
cb_trees: true
cb_veh_skins: true
cb_weather: true
cb_wheels: true
game_path: K:\ExMachinaRandomizer\game
language: rus
pos_x: -1435.0
pos_y: 86.0
preset: p_custom
version: cr114
