cb_ai_vehs: false
cb_aim: false
cb_armor: false
cb_bkgd: false
cb_books_history: false
cb_cab_cargo: false
cb_clans: false
cb_controls: false
cb_crashes: false
cb_descriptions: false
cb_dialogues: false
cb_digits: false
cb_dwellers: false
cb_engines: false
cb_env_models: false
cb_env_textures: false
cb_explosions: false
cb_fadingmsgs: false
cb_fov: false
cb_goods_guns: false
cb_gravity: false
cb_gui_icons: false
cb_gui_text: false
cb_guns: false
cb_guns_lua: false
cb_hits: false
cb_horns: false
cb_humans: false
cb_landscape: false
cb_lightmaps: false
cb_maps: false
cb_masks: false
cb_music: false
cb_names: false
cb_npc_look: false
cb_other_sounds: false
cb_pl_veh: false
cb_quests: false
cb_radar: false
cb_radio: false
cb_render: false
cb_shooting: false
cb_skybox: false
cb_speech: false
cb_splashes: false
cb_tiles: false
cb_towns: false
cb_trees: false
cb_veh_skins: false
cb_weather: false
cb_wheels: false
game_path: ""
game_version: ""
height: 706.0
is_maximized: false
language: eng
pos_x: 0.0
pos_y: 0.0
preset: ""
width: 880.0
